### ISSUE TITLE
HomeView Not Loading ContentsView

### ISSUE THREAD

**Issue by justbcuz** [barisozgenn/NetflixVisionPro#1]
Hi Baris,

This is a great project. THANK YOU for putting it together.

I am using Xcode 15 Beta 5 and when running in simulator HomeView does not seem to load ContentsView.

![Screenshot 2023-07-30 at 6 08 24 PM](https://github.com/barisozgenn/NetflixVisionPro/assets/186479/a29b6910-8905-4f85-82ad-ceb7df912877)

Could it be that ContentAPI is not loading before the ContentsView is rendered?

If I try and edit ContentsView, Preview seems to crash in Xcode. But that might be a Xcode Beta issue.

![Screenshot 2023-07-30 at 6 11 31 PM](https://github.com/barisozgenn/NetflixVisionPro/assets/186479/020181af-7d53-4f9c-941a-1c52b773d203)

Any help would be greatly appreciated.

Thanks,
Justin

**Comment by barisozgenn** [comment]
Hi Justin,
Thank you for providing such a detailed explanation and valuable feedback. I truly appreciate your efforts in examining the beta versions and sharing your thoughts.

I completely understand the challenges you faced while trying to simulate and monitor the project. Furthermore, I have been occupied with my some prior commitments, which delayed my progress in upgrading from beta 2 to 5. Additionally, beta 2 also presented some issues related to simulation and monitoring, leading me to decide on a cautious approach and waiting until a more stable beta version becomes available. I have mentioned this in the README file to keep everyone informed.

Currently, I may not be able to directly assist you due to my ongoing commitments. However, I have a potential solution that might help resolve the problem. In the next 1–2 weeks, I will be on vacation, and if the issue persists, I'll be more than happy to arrange a video call to provide closer assistance.

In the meantime, I suggest you follow these steps:

1. Search for the video variable strings in the project, such as "example-video," "example-avatar," and "netflix-intro-for-movie."
2. If these video names are not present in the asset folder, I might not have included them to avoid licensing issues. To address this, you can download free sample MP4 videos from providers like Google.
3. Import the downloaded videos into the asset folder using the same names you found in the first step. 
4. In the PlayerViewModel, the videos were captured using the GET API of a free video provider. It's possible that the links they return have changed, leading to loading issues. Please verify if those links are functioning correctly or consider replacing them with GET links from other free MP4 video providers like Google.

Kindly keep me updated on whether the issue is resolved or not. In case the problem persists, we can plan for further troubleshooting and finding a solution together at a later stage.

Thanks,
Baris

**Comment by jacopobonomi** [comment]
Hey @barisozgenn same problem, but videos are present and links works, any ideas?
